testing travis

diff --git a/refine b/refine
--- a/refine
+++ b/refine
@@ -480,15 +480,12 @@ test() {
 }
 
 ui_test() {
-    INTERACTIVE=$1
-    
-    windmill_prepare
-
     REFINE_DATA_DIR="${TMPDIR:=/tmp}/openrefine-tests"
     
     add_option "-Drefine.headless=true"
+    add_option "-Drefine.verbosity=error"
     
-    run fork
+    run fork > /dev/null
     
     echo "Waiting for OpenRefine to load..."
     sleep 5
@@ -499,15 +496,15 @@ ui_test() {
     echo "... proceed with the tests."
     echo ""
     
-    load_data "$REFINE_TEST_DIR/data/food.csv" "Food"
-    sleep 3
-    echo ""
-    
-    echo "Starting Windmill..."
-    if [ -z "$INTERACTIVE" ] ; then
-        "$WINDMILL" firefox firebug loglevel=WARN http://${REFINE_HOST}:${REFINE_PORT}/ jsdir=$REFINE_TEST_DIR/client/src exit
+    echo "Starting Cypress..." 
+    CYPRESS_RUN_CMD="yarn --cwd ./main/tests/cypress run cypress run --quiet --env OPENREFINE_URL=http://$REFINE_HOST:$REFINE_PORT"
+    echo "$CYPRESS_RUN_CMD"
+    exec $CYPRESS_RUN_CMD
+
+    if [ "$?" = "0" ] ; then
+        UI_TEST_SUCCESS="1"
     else
-        "$WINDMILL" firefox firebug loglevel=WARN http://${REFINE_HOST}:${REFINE_PORT}/
+        UI_TEST_SUCCESS="0"
     fi
     
     echo ""
@@ -515,6 +512,10 @@ ui_test() {
     /bin/kill -9 $REFINE_PID
     echo "Cleaning up"
     rm -rf "$REFINE_DATA_DIR"
+
+    if [ "$UI_TEST_SUCCESS" = "0" ] ; then
+        error "The UI test suite failed."
+    fi
 }
 
 server_test() {
